"""Export doctor summary to PDF or TXT."""
from reportlab.lib.pagesizes import letter
from reportlab.pdfgen import canvas
import io
import json
from datetime import datetime

DISCLAIMER = "DISCLAIMER: This document was generated by DocAssist AI based on user consultation & lab data. It is for informational support only and does NOT replace professional medical diagnosis or clinical judgment."

def export_to_pdf(summary) -> bytes:
    """Generate PDF using ReportLab with clean professional layout."""
    if isinstance(summary, str):
        try:
            summary = json.loads(summary)
        except Exception:
            summary = {'patient_concern': summary, 'symptoms': [], 'duration': 'N/A', 'report_findings': [], 'questions_for_doctor': []}
            
    if not isinstance(summary, dict):
        summary = {}

    buffer = io.BytesIO()
    c = canvas.Canvas(buffer, pagesize=letter)
    width, height = letter
    
    # Header Banner
    c.setFillColorRGB(0.08, 0.4, 0.75) # Primary medical blue
    c.rect(0, height - 80, width, 80, fill=True, stroke=False)
    
    c.setFillColorRGB(1, 1, 1)
    c.setFont("Helvetica-Bold", 20)
    c.drawString(50, height - 42, "DocAssist - Clinical Visit Summary")
    c.setFont("Helvetica", 10)
    gen_time = summary.get('generated_at') or datetime.now().strftime("%Y-%m-%d %H:%M")
    c.drawString(50, height - 62, f"Document Date: {gen_time} | Patient Consultation Record")
    
    c.setFillColorRGB(0.15, 0.15, 0.15)
    y = height - 110
    
    # Helper to draw sections
    def draw_section(title, content_items):
        nonlocal y
        if y < 100:
            c.showPage()
            y = height - 50
            
        c.setFont("Helvetica-Bold", 12)
        c.setFillColorRGB(0.08, 0.4, 0.75)
        c.drawString(50, y, title)
        c.line(50, y - 4, width - 50, y - 4)
        y -= 20
        
        c.setFont("Helvetica", 10)
        c.setFillColorRGB(0.2, 0.2, 0.2)
        
        if isinstance(content_items, str):
            content_items = [content_items]
            
        for item in content_items:
            if not item:
                continue
            if y < 80:
                c.showPage()
                y = height - 50
                c.setFont("Helvetica", 10)
                c.setFillColorRGB(0.2, 0.2, 0.2)
            c.drawString(60, y, f"• {str(item)[:90]}")
            y -= 16
        y -= 10

    # Section 1: Chief Concern
    concern = summary.get('patient_concern') or "Not specified"
    draw_section("1. Primary Patient Concern & Reason for Visit", [concern])
    
    # Section 2: Symptoms & Duration
    symptoms = summary.get('symptoms') or []
    duration = summary.get('duration') or "N/A"
    symptoms_list = [f"Symptoms reported: {', '.join(symptoms) if isinstance(symptoms, list) and symptoms else 'None noted'}", f"Reported Duration: {duration}"]
    draw_section("2. Reported Symptoms & Timeline", symptoms_list)
    
    # Section 3: Lab & Report Findings
    findings = summary.get('report_findings') or []
    if findings:
        draw_section("3. Diagnostic & Lab Report Findings", findings if isinstance(findings, list) else [str(findings)])
        
    # Section 4: Recommended Questions for Doctor
    questions = summary.get('questions_for_doctor') or []
    if questions:
        draw_section("4. Suggested Questions for Healthcare Provider", questions if isinstance(questions, list) else [str(questions)])

    # Footer Disclaimer
    c.setFont("Helvetica-Oblique", 8)
    c.setFillColorRGB(0.45, 0.45, 0.45)
    c.drawString(50, 40, DISCLAIMER[:110])
    c.drawString(50, 28, DISCLAIMER[110:])
    
    c.save()
    buffer.seek(0)
    return buffer.getvalue()

def export_to_txt(summary) -> str:
    """Plain text format with clean section headers."""
    if isinstance(summary, str):
        try:
            summary = json.loads(summary)
        except Exception:
            summary = {'patient_concern': summary, 'symptoms': [], 'duration': 'N/A'}
            
    if not isinstance(summary, dict):
        summary = {}

    lines = []
    lines.append("=" * 60)
    lines.append("DOCASSIST - CLINICAL VISIT & CONSULTATION SUMMARY")
    lines.append(f"Generated: {summary.get('generated_at', datetime.now().isoformat())}")
    lines.append("=" * 60)
    lines.append("")
    
    lines.append("1. PRIMARY PATIENT CONCERN:")
    lines.append(f"   {summary.get('patient_concern', 'None reported')}")
    lines.append("")
    
    lines.append("2. SYMPTOMS & DURATION:")
    symptoms = summary.get('symptoms', [])
    if isinstance(symptoms, list) and symptoms:
        for sym in symptoms:
            lines.append(f"   - {sym}")
    else:
        lines.append(f"   - {symptoms or 'None'}")
    lines.append(f"   Duration: {summary.get('duration', 'N/A')}")
    lines.append("")
    
    findings = summary.get('report_findings', [])
    if findings:
        lines.append("3. LAB & REPORT FINDINGS:")
        if isinstance(findings, list):
            for f in findings:
                lines.append(f"   - {f}")
        else:
            lines.append(f"   - {findings}")
        lines.append("")
        
    questions = summary.get('questions_for_doctor', [])
    if questions:
        lines.append("4. SUGGESTED QUESTIONS FOR DOCTOR:")
        if isinstance(questions, list):
            for q in questions:
                lines.append(f"   - {q}")
        else:
            lines.append(f"   - {questions}")
        lines.append("")
        
    lines.append("-" * 60)
    lines.append(DISCLAIMER)
    lines.append("-" * 60)
    
    return "\n".join(lines)

